train: 
  fake:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/train/fake/*/*/*
  real:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/train/real/*/*/*
validation:
  fake:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/validation/fake/*/*/*
  real:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/validation/real/*/*/*
test:
  fake:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/test/fake/*/*/*
  real:
  - /home/sands/Datas/TRAIN_AIGL_260106/mtcnn_20260106_x12_split/test/real/*/*/*

support_type:
- .png
- .jpg
- .jpeg
- .bmp
- .mp4
channel_format: RGB
